### ISSUE TITLE
您好，升级node之后，有警告提示 (node:19988) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated

### ISSUE THREAD

**Issue by nineaiyu** [condorheroblog/bundle-import#1]
您好，使用 vite-plugin-fake-server 这个包的时候，然后升级node22，有警告 (node:19988) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated

然后发现是该包 引入了 import-from-string ，并且import-from-string 又引入了 "import-meta-resolve": "^3.0.0"， 目前发现是 "import-meta-resolve": "^3.0.0" 有警告，你那里可以将这几个包都升级一下,兼容node22 么？

vite-plugin-fake-server => bundle-import => import-from-string => "import-meta-resolve": "^3.0.0"

**Comment by condorheroblog** [comment]
好的，已经完成请使用 [vite-plugin-fake-server v2.1.3](https://github.com/condorheroblog/vite-plugin-fake-server/releases/tag/v2.1.3)
